apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
      - name: dynamodb
        image: amazon/dynamodb-local:latest
        ports:
        - containerPort: 8000
        args: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb
spec:
  selector:
    app: dynamodb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
