apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-worker
  template:
    metadata:
      labels:
        app: payment-worker
    spec:
      containers:
      - name: payment-worker
        image: payment-worker:latest
        envFrom:
        - configMapRef:
            name: payment-worker-config
